image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  S3_BUCKET_NAME: "flutter.de"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - Node
  script:
  - hugo
  except:
  - master
  - develop

build master:
  stage: build
  tags:
    - Node
  script:
  - hugo --baseURL=http://flutter.de.s3-website.eu-central-1.amazonaws.com
  only:
  - master
  - develop
  artifacts:
    paths:
    - public
    expire_in: 1 hour

# pages:
#   stage: deploy
#   tags:
#     - Node
#   script:
#   - hugo
#   artifacts:
#     paths:
#     - public
#   only:
#   - develop
#   variables:
#     GIT_STRATEGY: none
#   artifacts:
#     paths:
#     - public
#     expire_in: 24 hour

deploy to production:
  stage: deploy
  dependencies: 
    - build master
  tags:
    - Node
  environment: production
  image: mikesir87/aws-cli
  script:
  - aws s3 cp public s3://flutter.de/ --recursive --acl public-read
  only:
  - master
  - develop
  variables:
    GIT_STRATEGY: none
  artifacts:
    paths:
    - public
    expire_in: 24 hour