image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  S3_BUCKET_NAME: "flutter.de"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - Node
  script:
  - hugo
  except:
  - master

build master:
  stage: build
  tags:
    - Node
  script:
  - hugo --baseURL=http://flutter.de.s3-website.eu-central-1.amazonaws.com
  only:
  - master

# pages:
#   stage: deploy
#   tags:
#     - Node
#   script:
#   - hugo
#   artifacts:
#     paths:
#     - public
#   only:
#   - develop

deploy to production:
  stage: deploy
  tags:
    - Node
  environment: production
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp public s3://flutter.de/ --recursive --acl public-read
  only:
  - develop