# image: registry.gitlab.com/pages/hugo/hugo_extended:latest
image: hugo:0.55.6-ext-nodejs

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  S3_BUCKET_NAME: "flutter.de"

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm install
    - npm --prefix ./themes/Fluttery install ./themes/Fluttery
    - PATH=$(npm bin):$PATH
    - hugo version
  tags:
    - Node
  script:
  - npm run build
  except:
  - master
  - develop

build master:
  stage: build
  before_script:
    - npm install
    - PATH=$(npm bin):$PATH
    - npm --prefix ./themes/Fluttery install ./themes/Fluttery
    - hugo version
  tags:
    - Node
  script:
  - npm run build:prod
  only:
  - master
  - develop
  artifacts:
    paths:
    - public
    expire_in: 8 hour

# pages:
#   stage: deploy
#   tags:
#     - Node
#   script:
#   - hugo
#   artifacts:
#     paths:
#     - public
#   only:
#   - develop
#   variables:
#     GIT_STRATEGY: none

deploy to production:
  stage: deploy
  dependencies: 
    - build master
  tags:
    - Node
  environment: production
  image: mikesir87/aws-cli
  script:
  - aws s3 cp public s3://flutter.de/ --recursive --acl public-read
  only:
  - master
  - develop
  variables:
    GIT_STRATEGY: none