image: registry.gitlab.com/pages/hugo/hugo_extended:0.74.3

stages:
  - build
  - release

# Build
build:
  stage: build
  before_script:
    - apk add --update nodejs npm
    - npm install
    - npm --prefix ./themes/fluttery install ./themes/fluttery
    - PATH=$(npm bin):$PATH
    - hugo version
  tags:
    - Node
  script:
    - npm run build:prod
  artifacts:
    paths:
    - public
    expire_in: 1 hour

# Static live deploy
Live Deploy:
  dependencies: 
    - build
  tags:
    - Node
  image: carimus/node-alpine-aws:node10
  stage: release
  script:
    - npm run deploy:s3
    - npm run cloudfront:invalidate
  only:
    - tags
  environment:
    name: Live
    url: https://www.flutter.de
